[package]
name = "chipo"
version = "0.1.0"
authors = ["lostptr <leosavis@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.9.1"
# Logs
env_logger = "0.11.3"
log = "0.4.27"
# Graphics
pixels = "0.15.0"
winit = "0.29"
