[package]
name = "chipo"
version = "0.1.0"
authors = ["SaviHex <leosavis@gmail.com>"]
edition = "2021"

[dependencies]
env_logger = "0.11.3"
pixels = "0.13.0"
winit = { version = "0.29.15", features = ["rwh_05"] }
winit_input_helper = "0.16.0"
rand = "0.8.5"
